# Generated by Django 5.2.10 on 2026-01-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=20, unique=True)),
                ('operator', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=4)),
                ('destination', models.CharField(max_length=4)),
                ('scheduled_arrival', models.DateTimeField(blank=True, null=True)),
                ('scheduled_departure', models.DateTimeField(blank=True, null=True)),
                ('altitude', models.FloatField(default=0.0)),
                ('fuel_mins', models.FloatField(default=0.0)),
                ('emergency_status', models.BooleanField(default=False)),
                ('zone_status', models.CharField(choices=[('LANDED', 'Landed'), ('RUNWAY_LA', 'On runway for landing'), ('RUNWAY_TO', 'On runway for takeoff'), ('QUEUE_LA', 'Queue to land (holding pattern)'), ('QUEUE_TO', 'Queue to takeoff'), ('DEPARTED', 'Departed')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runway_number', models.CharField(max_length=10)),
                ('length', models.IntegerField(help_text='Length in meters')),
                ('bearing', models.IntegerField(help_text='Heading in degrees')),
                ('operating_mode', models.CharField(default='Mixed', max_length=20)),
                ('operational_status', models.CharField(default='Available', max_length=20)),
            ],
        ),
    ]
