# Generated by Django 6.0.2 on 2026-03-06 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=20)),
                ('operator', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=4)),
                ('destination', models.CharField(max_length=4)),
                ('scheduled_arrival', models.DateTimeField(blank=True, null=True)),
                ('scheduled_departure', models.DateTimeField(blank=True, null=True)),
                ('queue_entry_time', models.DateTimeField(blank=True, null=True)),
                ('altitude', models.IntegerField(default=0)),
                ('fuel_mins', models.IntegerField(default=0)),
                ('emergency_status', models.CharField(choices=[('NONE', 'None'), ('FUEL', 'Low Fuel'), ('MECHANICAL', 'Mechanical Failure'), ('MEDICAL', 'Passenger Health')], default='NONE', max_length=20)),
                ('zone_status', models.CharField(choices=[('SCHEDULED', 'In schedule (Hidden)'), ('LANDED', 'Landed'), ('RUNWAY_LA', 'On runway for landing'), ('RUNWAY_TO', 'On runway for takeoff'), ('QUEUE_LA', 'Queue to land (holding pattern)'), ('QUEUE_TO', 'Queue to takeoff'), ('DEPARTED', 'Departed'), ('CANCELLED', 'Cancelled'), ('DIVERTED', 'Diverted')], max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holding_time_mins', models.FloatField(default=0.0)),
                ('takeoff_queue_time_mins', models.FloatField(default=0.0)),
                ('arrival_delay_mins', models.FloatField(default=0.0)),
                ('departure_delay_mins', models.FloatField(default=0.0)),
                ('holding_time_variance', models.FloatField(default=0.0)),
                ('takeoff_queue_time_variance', models.FloatField(default=0.0)),
                ('arrival_delay_variance', models.FloatField(default=0.0)),
                ('departure_delay_variance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(help_text='Length in meters')),
                ('bearing', models.IntegerField(help_text='Heading in degrees')),
                ('operating_mode', models.CharField(choices=[('LANDING', 'Landing'), ('TAKEOFF', 'Takeoff'), ('MIXED', 'Mixed')], max_length=20)),
                ('time_occupied', models.DateTimeField(blank=True, null=True)),
                ('operational_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RUNWAYINSPEC', 'Runway Inspection'), ('SNOWCLEAR', 'Snow Clearance'), ('EQUIPFAIL', 'Equipment Failure'), ('OCCUPIED', 'Occupied')], max_length=20)),
                ('temp_optimised', models.BooleanField(default=False)),
                ('occupied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_runway', to='simulation.aircraft')),
            ],
        ),
        migrations.AddField(
            model_name='aircraft',
            name='assigned_runway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulation.runway'),
        ),
    ]
