# Generated by Django 6.0.2 on 2026-02-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=20)),
                ('holding_time_mins', models.FloatField(default=0.0)),
                ('takeoff_queue_time_mins', models.FloatField(default=0.0)),
                ('arrival_delay_mins', models.FloatField(default=0.0)),
                ('departure_delay_mins', models.FloatField(default=0.0)),
                ('outcome', models.CharField(choices=[('LANDED', 'Landed'), ('DEPARTED', 'Departed'), ('CANCELLED', 'Cancelled'), ('DIVERTED', 'Diverted')], default='LANDED', max_length=20)),
                ('time_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='aircraft',
            name='assigned_runway',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='queue_entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='zone_status',
            field=models.CharField(choices=[('SCHEDULED', 'In schedule (Hidden)'), ('LANDED', 'Landed'), ('RUNWAY_LA', 'On runway for landing'), ('RUNWAY_TO', 'On runway for takeoff'), ('QUEUE_LA', 'Queue to land (holding pattern)'), ('QUEUE_TO', 'Queue to takeoff'), ('DEPARTED', 'Departed'), ('CANCELLED', 'Cancelled'), ('DIVERTED', 'Diverted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='runway',
            name='operating_mode',
            field=models.CharField(choices=[('LANDING', 'Landing'), ('TAKEOFF', 'Takeoff'), ('MIXED', 'Mixed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='runway',
            name='operational_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RUNWAYINSPEC', 'Runway Inspection'), ('SNOWCLEAR', 'Snow Clearance'), ('EQUIPFAIL', 'Equipment Failure'), ('OCCUPIED', 'Occupied')], max_length=20),
        ),
        migrations.AlterField(
            model_name='runway',
            name='runway_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
