# Generated by Django 5.2.11 on 2026-03-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runways', models.IntegerField()),
                ('operating_mode', models.CharField(choices=[('LANDING', 'Landing'), ('TAKEOFF', 'Takeoff'), ('MIXED', 'Mixed')], max_length=20)),
                ('inbound_per_hour', models.IntegerField()),
                ('outbound_per_hour', models.IntegerField()),
                ('timescale', models.FloatField(default=1.0)),
                ('schedule_limit', models.IntegerField(default=2)),
                ('max_wait', models.IntegerField()),
                ('landing_duration', models.IntegerField(default=45)),
                ('takeoff_duration', models.IntegerField(default=45)),
                ('fuel_risk_threshold', models.IntegerField(default=20)),
                ('takeoff_risk_threshold', models.IntegerField(default=25)),
                ('random_events', models.BooleanField()),
                ('stop', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='runway',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
