# Generated by Django 5.2.11 on 2026-03-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_alter_aircraft_id_alter_runconfig_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='final_state_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
