# Generated by Django 6.0.2 on 2026-02-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_flightstats_aircraft_assigned_runway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runway',
            name='temp_optimised',
            field=models.BooleanField(default=False),
        ),
    ]
