# Generated by Django 6.0.2 on 2026-02-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_runway_temp_optimised'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='callsign',
            field=models.CharField(max_length=20),
        ),
    ]
